name       : onevpl
version    : 2023.1.1
release    : 1
source     :
    - https://github.com/oneapi-src/oneVPL/archive/refs/tags/v2023.1.1.tar.gz : f3973f98b08564fd529079911c4e64cd5b552f6933a4a71d085609db6e5de09a
license    : MIT
component  : multimedia.library
summary    : oneAPI Video Processing Library (oneVPL) dispatcher
description: |
    The oneAPI Video Processing Library (oneVPL) is a programming interface for video decoding, encoding, and processing to build portable media pipelines on CPUs, GPUs, and other accelerators.
    It provides device discovery and selection in media centric and video analytics workloads and API primitives for zero-copy buffer sharing. oneVPL is backwards and cross-architecture compatible to ensure optimal execution on current and next generation hardware without source code changes.
patterns   :
    - devel:
        - /usr/etc/
setup      : |
    %cmake_ninja \
        -DBUILD_PREVIEW=OFF \
        -DBUILD_TOOLS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Remove unneeded docs
    rm -rfv $installdir/usr/share/
    # Remove unneeded devel files
    rm -rfv $installdir/usr/etc/